services:
  bybit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bybit
    restart: unless-stopped
    env_file:
      - .env                   # переменные окружения для pydantic Settings
    working_dir: /app
    command: ["poetry", "run", "python", "-u", "src/main.py"]
    volumes:
      # (не обязательно) рабочий каталог, чтобы видеть лок-файл и логи с хоста
      - ./data:/app/data
    networks:
      - bybit-net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

networks:
  bybit-net:
    driver: bridge
