services:
  bybit:
    build: .
    container_name: bybit
    restart: always
    env_file:
      - .env
    networks:
      - bybit-net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
networks:
  bybit-net:
    driver: bridge